### ISSUE TITLE
Build fails with Bioconductor devel (3.11) on Windows 10 with R 4.0.0-testing and Rtools 4.0 toolchain

### ISSUE THREAD

**Issue by andzajan** [Bioconductor/zlibbioc#1]
Rtools 4.0 toolchain for Windows installs all it's packages in the folders _/mingw32/bin_ and _/mingw64/bin_

When I do attmep to install _zlibbioc_ using command _BiocManager::install("zlibbioc")_, compilation fails as by default _gcc_ path for 32-bit architecture is set to folded _/mingw/bin_.

As there is no easy way to override gcc configuration parameters, it probably would make sense to set _i386_ gcc path to default value of _/mingw32/bin/gcc_.

Quick and dirty solution is to copy contents of _mingw32_ folder to _mingw_ within installation folder or _Rtools_.

Why does _BiocManager::install("zlibbioc")_ is compiling both _i386_ and _x64_ binaries on 64-bit operating system?

`
R version 4.0.0 Under development (Rtools 4.0) (2019-11-23 r77455)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252
`

**Comment by andzajan** [comment]
Just to clarify, all other Bioconductor pakcages I was compling today were using correct _gcc_ path _/mingw32/bin/gcc_. Based on this observation I believe that this rleted to **zlibbioc** directly.

**Comment by mtmorgan** [comment]
An easier solution is to install the binary version of the package, via `options(pkgType = "both")` (the default for that option)?

**Comment by andzajan** [comment]
R 4.0.0 testing can't find binary version for _zlibbioc_, that's why it defaults to compile it from source.

**Comment by mtmorgan** [comment]
zlibbioc is available for that platform; here is the build report http://bioconductor.org/checkResults/3.11/bioc-LATEST/zlibbioc/malbec2-checksrc.html 'landing page http://bioconductor.org/packages/3.11/bioc/html/zlibbioc.html and .zip archive http://bioconductor.org/packages/3.11/bioc/bin/windows/contrib/4.0/zlibbioc_1.33.0.zip

Can you provide the full output of `BiocManager::install('zlibbioc')`?

**Comment by andzajan** [comment]
Hi @mtmorgan, this appers to be only `R-testing` and not `R-devel` related. R-devel seems to be able to acess repositories for binary packages.
R-testing is trying to access non-existing link I guess?

`> BiocManager::install('zlibbioc')`

`Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.0 Under development (Rtools 4.0) (2019-11-23 r77455)
Installing package(s) 'zlibbioc'
Warning: unable to access index for repository https://bioconductor.org/packages/3.11/bioc/bin/windows/contrib/4.0gcc8:
  cannot open URL 'https://bioconductor.org/packages/3.11/bioc/bin/windows/contrib/4.0gcc8/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0gcc8:
  cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/windows/contrib/4.0gcc8/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0gcc8:
  cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/windows/contrib/4.0gcc8/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0gcc8:
  cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/windows/contrib/4.0gcc8/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘zlibbioc’
Installation path not writeable, unable to update packages: Matrix, nlme, survival
Old packages: 'digest', 'plyr', 'rlang'
Update all/some/none? [a/s/n]: `

**Comment by hpages** [comment]
Hi @andzajan ,

We've added the 4.0gcc8 -> 4.0 symlink to the Bioconductor package repositories so now you should be able to access the package binaries for Windows with R 4.0.0-testing. However, please note that we're not using the Rtools 4.0 toolchain yet on our Windows builders (we're still using Rtools 3.4.0.1962) so the Windows binaries we're providing at the moment for BioC 3.11 users might not be compatible with R 4.0.0-testing. In other words, we're not supporting R 4.0.0-testing yet.

Best,
H.

**Comment by hpages** [comment]
Closing this. @andzajan Feel free to re-open if you're still having problems with this.
